version: "3.3"

services:

  winbox:
    image: cnsoluciones/novnc-winbox:latest
    container_name: winbox
    restart: always
    #volumes:
    # - ./user-data/.wine:/home/alpine/.wine
    ports:
      - "5901:5900"
      - "18081:8080"
    network_mode: bridge
